### ISSUE TITLE
No screenshot on tweets, Selenium timeout exception

### ISSUE THREAD

**Issue by OKIE8T9** [kevinabrandon/AboveTustin#11]
Getting the following error when I start AboveTustin: 
`class 'selenium.common.exceptions.TimeoutException`

I appreciate the help!

**Comment by kevinabrandon** [comment]
@ktul584 did you ever resolve this?  I've never seen the error on my system.

**Comment by OKIE8T9** [comment]
Hey brandon! Sorry this has been on the back burner for awhile. I started everything from a fresh install today using Stretch, and still getting the error:
```
***** Restarting AboveTustin  2017-11-18 16:56:20.064071883+00:00

will crop
getting web page...
waiting for page to load...
exception in loadmap()
<class 'selenium.common.exceptions.TimeoutException'>
unable to load browser!

```

**Comment by kevinabrandon** [comment]
A few thoughts...

First, I very recently made some stability updates so make sure you have the latest code.

Second there should be a ghostscript.log file created... take a peek in there for possible hints.

Third, I just reinstalled the project on a brand new raspberry pi 3 using [jprochazka’s adsb-receiver project](https://github.com/jprochazka/adsb-receiver).  However I ran into some problems which I detailed [here](http://adsbreceiver.net/forum/thread/abovetustin-setup/).

Good luck!

**Comment by OKIE8T9** [comment]
Here's what's in ghostscript.log:

```
phantomjs://platform/console++.js:263 in error
[ERROR - 2017-11-18T19:42:24.908Z] WebElementLocator - _handleLocateCommand - Element(s) NOT Found: GAVE UP. Search Stop Time: 1511034144862
```

**Comment by kevinabrandon** [comment]
So the script is looking for the reset map link on the dump1090-mutability page.  Then it looks for the zoom button.  Are you using something other than dump1090 mutability?

**Comment by OKIE8T9** [comment]
I am using dump1090-FA, should I switch to mutability?

**Comment by kevinabrandon** [comment]
yeah, I've never used the dump1090-fa branch, so I don't know how it works.
I've had a few people ask about supporting it though.  Can you do at least a quick check for me?
Go to the directory AboveTustin is installed and run the following command: `python3 flightdata.py`  Does it immediately crash?  Or does it show a table of current flights (make sure the terminal window is large enough to view properly)?

If that program works, supporting the dump1090-fa branch shouldn't be that hard.

**Comment by OKIE8T9** [comment]
I wound up switching to mutability and that fixed it
