### ISSUE TITLE
FA API - Authentication Required

### ISSUE THREAD

**Issue by hbokh** [kevinabrandon/AboveTustin#33]
Somehow the FlightAware API requires extra authentication besides "username" and "apikey" (cc @wiseman). This is the output (while testing the VRS-driver):

```
time to create screenshot of <AirCraftData 461F9E/OH-LZI/FIN47U dist=48.93611981682591 el=3.2672329871863455>:
success saving screenshot: tweet.png
Getting FlightAware flight details
FA API status code: 401
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
<title>Authentication Required</title>
</head>
<body>
<h1>Authentication Required</h1>


</body>
</html>

time to tweet!!!!!
#FIN47U: 78.8 km away @ 4495.8 m and 3.3° frm hrzn, heading SW @ 655.8km/h 09:25:18. #MovingQuickly #AboveGRQ #ADSB
```

**Comment by hbokh** [comment]
FYI There seems to be different API v2 and v3 keys... Was using the v2. Trying to work it out.

**Comment by hbokh** [comment]
**SOLVED** Working with v3 API-key only (I used a v2 API-key at first).
Two tweets on flight SAS540:
- dump1090: https://twitter.com/AboveGrq/status/950685256721616896 (actual plane out of bounds in map, see VRS next)
- VRS: https://twitter.com/AboveGrq/status/950686506821279749 (altitude shows feet as meters)

**Comment by wiseman** [comment]
Glad you figured it out, and thanks for doing some more testing of the VRS driver.
