### ISSUE TITLE
Support for metric units

### ISSUE THREAD

**Issue by Romeo-Golf** [kevinabrandon/AboveTustin#4]
At least if dump1090 is configured to use metric units, but ideally an option for the user to choose between :)

**Comment by kevinabrandon** [comment]
Yes this is needed.

**Comment by kevinabrandon** [comment]
Check out the new tweet template and sample config, you can add different variables with mixed units to the tweet.  For example for distance you can use: ${dist-mi}, ${dist-km} or ${dist-nm}.  Same thing applies for altitude, speed and vertical speed.
