### ISSUE TITLE
Alarm Zone - Distance Alarm tweaks? 

### ISSUE THREAD

**Issue by Bering-Sea** [kevinabrandon/AboveTustin#40]
@kevinabrandon  My setup is about a 1/4 mile from the runway and would like to catch planes on approach and leaving the runway. My setup has a 5 mile distance alarm i just get the plane taxiing on ramp. I set it up for 5 miles to catch the planes passing overhead my location. Very little traffic below 30,000 feet at my location. It tweets planes flying by overhead fine. 

I don't know much coding. Just tweak written code or copy, paste and delete for now.

Can my distance alarm not include the first mile and start from 2 miles to 5 miles?

**Comment by Bering-Sea** [comment]
That question of distance alarm answered itself last night. 

So I still have the same dilemma. Can I have the my elevation alarm be a range and not just one number? 

distance_alarm = 1
elevation_alarm = **10 to 30**  <-----???

is that possible?

**Comment by kevinabrandon** [comment]
So you could do that but you'd have to change the code on [line 170 of tracker.py](https://github.com/kevinabrandon/AboveTustin/blob/master/tracker.py#L170).

Currently it's:
`if a.distance < abovetustin_distance_alarm or a.el > abovetustin_elevation_alarm:`
and change it to something like:
`if a.distance < 1 or (a.el > 10 and a.el < 30):`

If you want you could rename the elevation_alarm in the ini file to elevation_alarm_min and add an elevation_alarm_max and then other people might do similar.

**Comment by Bering-Sea** [comment]
@kevinabrandon Great! I'll do that, thanks!
