### ISSUE TITLE
Twitter module not found and installation help

### ISSUE THREAD

**Issue by shadowpants18** [kevinabrandon/AboveTustin#42]
I'm very new to coding, so maybe this is a dumb question, but I keep getting the error module not install - twitter, but I installed it through pip, and when I run pip list, twitter is on there. 
Also, are there installation instructions I can follow anywhere?

**Comment by Spcktr** [comment]
In the base folder run `pip install -r requirements.txt` that will install all the required dependencies globally.

**Comment by shadowpants18** [comment]
I reinstalled everything by hand since -r requirements.txt kept failing. Also, on run_tacker.sh, what should I be putting for cs and source?

**Comment by Spcktr** [comment]
In the example:
```
cd /home/pi/AboveTustin
source py3/bin/activate
```
So `cd` would be where you have the AboveTustin folder located, and the source is to activate the virtual env that should have been made.

So, basically,
1. Clone the repository
2. Create a python virtual environment inside that new cloned folder `python3 -m venv venv`
3. Then run `source venv/bin/activate` 
4. Run `pip3 install -r requirements.txt` if that fails `python3 -m pip install -r requirements.txt`
5. Once pip has installed the required deps type `deactivate`
6. In the `run_tracker.sh` file edit the line `cd /home/pi/AboveTustin` to match where the folder is located
7. Edit the `source` line to match the location of the virtual environment is; eg `/home/pi/AboveTustin/venv/bin/activate`
8. `chmod +x run_tracker.sh` (this makes the file executable, may require `sudo`)
9. Copy the `config.sample.ini` file with `cp config.sample.ini config.ini`
10. Edit the new config.ini file with details for you accounts, latitude and longitude, which driver, etc
11. then ./run_tracker.sh and it should be working.

Think that is everything.

**Comment by shadowpants18** [comment]
great thank you so much!
