### ISSUE TITLE
Cantenna instructions link broken

### ISSUE THREAD

**Issue by Fortyseven** [kevinabrandon/AboveTustin#45]
While sharing this with a friend, it was noted that the 'cantenna' instructions link in the README no longer points to the thread in question. Now it redirects to the root of the forum. Not sure how you want to handle that -- the thread can probably be fished out again via a forum search... but I figure if it broke once, it'll break again. 😅 

Anyway, here's an archive.org link: https://web.archive.org/web/20170909005202/https://www.adsbexchange.com/forums/topic/beginners-2-cantenna-easy-diy-antenna-to-improve-rangeplane-count/

**Comment by big-dasher** [comment]
Hi. I'm sure that this was meant for another Darren gray. This email
address is not the email address of the person you are trying to contact.


Happy hunting

Daz

**Comment by kevinabrandon** [comment]
Thanks @Fortyseven for the heads up!
